### ISSUE TITLE
code error 

### ISSUE THREAD

**Issue by W1V1995** [divya031090/TaxoNN_OTU#1]
Your method is pretty good,but when I run the code,I have a errror like this:

OSError: Unable to open file (unable to open file: name = 'model_1_T2D.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

and I don't know how to handle this issue,maybe you can help me.
Appreciate!

**Comment by divya031090** [comment]
Hi! you can train and save the model as a .h5 file. Not saved here because of the size. Basically after running the iterations the learned features are save in these files.
